version: '3.8'

services:
  mysql:
    image: mysql:8.0.36-debian
    container_name: watch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WATCH_AURA
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - watch-data:/var/lib/mysql
    networks:
      - watch-network

  app:
    build: .   # build từ Dockerfile
    container_name: mysql-watch-store
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/WATCH_AURA
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - watch-network

volumes:
  watch-data:

networks:
  watch-network:
    driver: bridge
