server:
  port: 8080
  servlet:
    context-path: /watch_aura
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/WATCH_AURA}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  security:
    user:
      name: user
      password: ''
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
jwt:
  signerKey: "PzcEXHkagVn34ElrlcOUQLazHeIg86xNVPk5Fj94TzH0RyCLngqSyPmzUtWc7yyP"
  expirationTime: 86400000spring.application.name=watch-store-be
